In [2]:
import os
#!pip install sql_metadata
#!pip install sqlparse

In [3]:
for pathroot, _, files in os.walk('../data/'):
    print(files)

['sample_query.sql']

In [4]:
FILE = '../data/sample_query.sql'

In [5]:
with open(FILE,'r') as f:
    lines = f.read()

In [10]:
print(lines)

WITH cte_region_territories AS (
  select
  level2_territory_key,
  level2_territory_full_name,
  level3_territory_full_name, -- added level3 territory info to avoid to populate NA value in dashboard.
  t.field_force
  from analytics.map_territory_hierarchy mth
  inner join analytics.dim_territory t
  on mth.level2_territory_key= t. territory_key
  where mth.sys_current_flag= true
  and t.sys_current_flag= true and t.sys_deleted_flag=false
  group by level3_territory_full_name, -- added level3 territory info to avoid to populate NA value in dashboard.
  level2_territory_full_name,
  level2_territory_key,
  t.field_force
),

-- added filter to show only the detailed products in Xsight reporting CD-6394
cte_dim_product as (
select * from analytics.dim_product
where product_type='Detail'
)

SELECT
  '-' as sys_created_on,
  '-' as sys_created_by,
  '-' as sys_created_id,
  fae.country_code as sys_tenant,
  fae.country_code,
  dct.country_name,
  dct.country_level_4 as country_group,
  dct.country_level_3 as subregion,
  dct.country_level_2 as regional_cluster,
  coalesce(dp.brand_name,'NA') as brand_name,
  coalesce(dp.product_name,'NA') as product_name,
  coalesce(vraps.account_product_segment, 'not segmented' ) AS segment,
  coalesce(mth.level1_territory_key, rt.level2_territory_key, 'NA') as territory_key,
  coalesce(mth.level1_territory_full_name, rt.level2_territory_full_name, 'NA') as territory_full_name,
  coalesce(mth.field_force,rt.field_force,mth.level3_territory_full_name, rt.level3_territory_full_name,'NA') as field_force, -- modified to populate level3 territory name when field force value is null for NA issue in dashboard
  coalesce(mth.level2_territory_key, rt.level2_territory_key,'NA') as region_key,
  coalesce(mth.level2_territory_full_name, rt.level2_territory_full_name, 'NA') as region,
  fae.email_clicked_flag,
  fae.email_opened_flag,
  fae.email_status,
  fae.email_sent_date,
  da.account_id,
  fae.email_sent_id,
  fae.product_key,
  fae.account_target_flag as target_flag,
  date_trunc('year',date(email_sent_date)) as year_start_date,
  -- dateadd(day, -1, dateadd(year,1,date_trunc('year',date(email_sent_date)))) as year_end_date,
  date_trunc('year',date(email_sent_date) + interval '1' year - interval '1' day as year_end_date,
  date_trunc('month',date(email_sent_date)) as month_start_date,
  -- dateadd(day, -1, dateadd(month,1,date_trunc('month',date(email_sent_date)))) as month_end_date,
  -- date_trunc('month', current_date) - interval 1 month as prev_mnth,
  case when date_trunc('month', current_date) = date_trunc('month', email_sent_date) then 'C'
  when date_trunc('month', current_date) - interval '1' month = date_trunc('month', email_sent_date) then 'P'
  when date_trunc('month', current_date) - interval '2' month = date_trunc('month', email_sent_date) then 'PP'
  when date_trunc('month', current_date) - interval '3' month = date_trunc('month', email_sent_date) then 'PPP'
  else NULL
  end as month_period,
  fae.employee_key
FROM analytics.DIM_ACCOUNT AS da
INNER JOIN analytics.FACT_APPROVED_EMAIL AS fae
  ON da.account_key = fae.account_key
  AND da.sys_current_flag = TRUE
LEFT JOIN cte_dim_product AS dp
  ON dp.product_key = fae.product_key
  AND dp.sys_current_flag = TRUE
LEFT JOIN analytics.vw_rep_account_product_segmentation AS vraps
  ON vraps.product_key = fae.product_key
  AND vraps.account_key = fae.account_key
LEFT JOIN analytics.map_territory_hierarchy AS mth
  ON fae.territory_key = mth.level1_territory_key
  AND mth.sys_current_flag = true
LEFT JOIN analytics.dim_territory AS dt
  ON fae.territory_key = dt.territory_key
  AND dt.sys_current_flag = true
LEFT JOIN cte_region_territories AS rt
  ON rt.level2_territory_key= fae.territory_key
LEFT JOIN analytics.dim_country as dct on dct.country_code = fae.country_code
WHERE 1=1
and fae.business_function_key != '4'
and ( fae.territory_key IS NULL OR mth.level1_territory_full_name IS NOT NULL OR rt.level2_territory_key IS NOT NULL)

In [6]:
from sql_metadata import Parser

tokens = Parser(lines).tokens

tokens[10]

SQLToken(position=10,value=,,is_keyword=False,is_name=False,is_punctuation=True,is_dot=False,is_wildcard=False,is_integer=False,is_float=False,is_comment=False,is_left_parenthesis=False,is_right_parenthesis=False,last_keyword=SELECT,next_token=-- added level3 territory info to avoid to populate NA value in dashboard.
,previous_token=level3_territory_full_name,subquery_level=0,is_in_nested_function=False,parenthesis_level=1,is_subquery_start=False,is_subquery_end=False,is_with_query_start=False,is_with_query_end=False,is_with_columns_start=False,is_with_columns_end=False,is_nested_function_start=False,is_nested_function_end=False,is_column_definition_start=False,is_column_definition_end=False,is_create_table_columns_declaration_start=False,is_create_table_columns_declaration_end=False)

In [14]:
content = [(t.position, t.value) for t in tokens]

AttributeError: 'str' object has no attribute 'position'

In [15]:
content

[(0, 'WITH'),
 (1, 'cte_region_territories'),
 (2, 'AS'),
 (3, '('),
 (4, 'select'),
 (5, 'level2_territory_key'),
 (6, ','),
 (7, 'level2_territory_full_name'),
 (8, ','),
 (9, 'level3_territory_full_name'),
 (10, ','),
 (11,
  '-- added level3 territory info to avoid to populate NA value in dashboard.\n'),
 (12, 't'),
 (13, '.'),
 (14, 'field_force'),
 (15, 'from'),
 (16, 'analytics'),
 (17, '.'),
 (18, 'map_territory_hierarchy'),
 (19, 'mth'),
 (20, 'inner join'),
 (21, 'analytics'),
 (22, '.'),
 (23, 'dim_territory'),
 (24, 't'),
 (25, 'on'),
 (26, 'mth'),
 (27, '.'),
 (28, 'level2_territory_key'),
 (29, '='),
 (30, 't'),
 (31, '.'),
 (32, 'territory_key'),
 (33, 'where'),
 (34, 'mth'),
 (35, '.'),
 (36, 'sys_current_flag'),
 (37, '='),
 (38, 'true'),
 (39, 'and'),
 (40, 't'),
 (41, '.'),
 (42, 'sys_current_flag'),
 (43, '='),
 (44, 'true'),
 (45, 'and'),
 (46, 't'),
 (47, '.'),
 (48, 'sys_deleted_flag'),
 (49, '='),
 (50, 'false'),
 (51, 'group by'),
 (52, 'level3_territory_full_name'),
 (53, ','),
 (54,
  '-- added level3 territory info to avoid to populate NA value in dashboard.\n'),
 (55, 'level2_territory_full_name'),
 (56, ','),
 (57, 'level2_territory_key'),
 (58, ','),
 (59, 't'),
 (60, '.'),
 (61, 'field_force'),
 (62, ')'),
 (63, ','),
 (64,
  '-- added filter to show only the detailed products in Xsight reporting CD-6394\n'),
 (65, 'cte_dim_product'),
 (66, 'as'),
 (67, '('),
 (68, 'select'),
 (69, '*'),
 (70, 'from'),
 (71, 'analytics'),
 (72, '.'),
 (73, 'dim_product'),
 (74, 'where'),
 (75, 'product_type'),
 (76, '='),
 (77, "'Detail'"),
 (78, ')'),
 (79, 'SELECT'),
 (80, "'-'"),
 (81, 'as'),
 (82, 'sys_created_on'),
 (83, ','),
 (84, "'-'"),
 (85, 'as'),
 (86, 'sys_created_by'),
 (87, ','),
 (88, "'-'"),
 (89, 'as'),
 (90, 'sys_created_id'),
 (91, ','),
 (92, 'fae'),
 (93, '.'),
 (94, 'country_code'),
 (95, 'as'),
 (96, 'sys_tenant'),
 (97, ','),
 (98, 'fae'),
 (99, '.'),
 (100, 'country_code'),
 (101, ','),
 (102, 'dct'),
 (103, '.'),
 (104, 'country_name'),
 (105, ','),
 (106, 'dct'),
 (107, '.'),
 (108, 'country_level_4'),
 (109, 'as'),
 (110, 'country_group'),
 (111, ','),
 (112, 'dct'),
 (113, '.'),
 (114, 'country_level_3'),
 (115, 'as'),
 (116, 'subregion'),
 (117, ','),
 (118, 'dct'),
 (119, '.'),
 (120, 'country_level_2'),
 (121, 'as'),
 (122, 'regional_cluster'),
 (123, ','),
 (124, 'coalesce'),
 (125, '('),
 (126, 'dp'),
 (127, '.'),
 (128, 'brand_name'),
 (129, ','),
 (130, "'NA'"),
 (131, ')'),
 (132, 'as'),
 (133, 'brand_name'),
 (134, ','),
 (135, 'coalesce'),
 (136, '('),
 (137, 'dp'),
 (138, '.'),
 (139, 'product_name'),
 (140, ','),
 (141, "'NA'"),
 (142, ')'),
 (143, 'as'),
 (144, 'product_name'),
 (145, ','),
 (146, 'coalesce'),
 (147, '('),
 (148, 'vraps'),
 (149, '.'),
 (150, 'account_product_segment'),
 (151, ','),
 (152, "'not segmented'"),
 (153, ')'),
 (154, 'AS'),
 (155, 'segment'),
 (156, ','),
 (157, 'coalesce'),
 (158, '('),
 (159, 'mth'),
 (160, '.'),
 (161, 'level1_territory_key'),
 (162, ','),
 (163, 'rt'),
 (164, '.'),
 (165, 'level2_territory_key'),
 (166, ','),
 (167, "'NA'"),
 (168, ')'),
 (169, 'as'),
 (170, 'territory_key'),
 (171, ','),
 (172, 'coalesce'),
 (173, '('),
 (174, 'mth'),
 (175, '.'),
 (176, 'level1_territory_full_name'),
 (177, ','),
 (178, 'rt'),
 (179, '.'),
 (180, 'level2_territory_full_name'),
 (181, ','),
 (182, "'NA'"),
 (183, ')'),
 (184, 'as'),
 (185, 'territory_full_name'),
 (186, ','),
 (187, 'coalesce'),
 (188, '('),
 (189, 'mth'),
 (190, '.'),
 (191, 'field_force'),
 (192, ','),
 (193, 'rt'),
 (194, '.'),
 (195, 'field_force'),
 (196, ','),
 (197, 'mth'),
 (198, '.'),
 (199, 'level3_territory_full_name'),
 (200, ','),
 (201, 'rt'),
 (202, '.'),
 (203, 'level3_territory_full_name'),
 (204, ','),
 (205, "'NA'"),
 (206, ')'),
 (207, 'as'),
 (208, 'field_force'),
 (209, ','),
 (210,
  '-- modified to populate level3 territory name when field force value is null for NA issue in dashboard\n'),
 (211, 'coalesce'),
 (212, '('),
 (213, 'mth'),
 (214, '.'),
 (215, 'level2_territory_key'),
 (216, ','),
 (217, 'rt'),
 (218, '.'),
 (219, 'level2_territory_key'),
 (220, ','),
 (221, "'NA'"),
 (222, ')'),
 (223, 'as'),
 (224, 'region_key'),
 (225, ','),
 (226, 'coalesce'),
 (227, '('),
 (228, 'mth'),
 (229, '.'),
 (230, 'level2_territory_full_name'),
 (231, ','),
 (232, 'rt'),
 (233, '.'),
 (234, 'level2_territory_full_name'),
 (235, ','),
 (236, "'NA'"),
 (237, ')'),
 (238, 'as'),
 (239, 'region'),
 (240, ','),
 (241, 'fae'),
 (242, '.'),
 (243, 'email_clicked_flag'),
 (244, ','),
 (245, 'fae'),
 (246, '.'),
 (247, 'email_opened_flag'),
 (248, ','),
 (249, 'fae'),
 (250, '.'),
 (251, 'email_status'),
 (252, ','),
 (253, 'fae'),
 (254, '.'),
 (255, 'email_sent_date'),
 (256, ','),
 (257, 'da'),
 (258, '.'),
 (259, 'account_id'),
 (260, ','),
 (261, 'fae'),
 (262, '.'),
 (263, 'email_sent_id'),
 (264, ','),
 (265, 'fae'),
 (266, '.'),
 (267, 'product_key'),
 (268, ','),
 (269, 'fae'),
 (270, '.'),
 (271, 'account_target_flag'),
 (272, 'as'),
 (273, 'target_flag'),
 (274, ','),
 (275, 'date_trunc'),
 (276, '('),
 (277, "'year'"),
 (278, ','),
 (279, 'date'),
 (280, '('),
 (281, 'email_sent_date'),
 (282, ')'),
 (283, ')'),
 (284, 'as'),
 (285, 'year_start_date'),
 (286, ','),
 (287,
  "-- dateadd(day, -1, dateadd(year,1,date_trunc('year',date(email_sent_date)))) as year_end_date,\n"),
 (288, 'date_trunc'),
 (289, '('),
 (290, "'year'"),
 (291, ','),
 (292, 'date'),
 (293, '('),
 (294, 'email_sent_date'),
 (295, ')'),
 (296, '+'),
 (297, 'interval'),
 (298, "'1'"),
 (299, 'year'),
 (300, '-'),
 (301, 'interval'),
 (302, "'1'"),
 (303, 'day'),
 (304, 'as'),
 (305, 'year_end_date'),
 (306, ','),
 (307, 'date_trunc'),
 (308, '('),
 (309, "'month'"),
 (310, ','),
 (311, 'date'),
 (312, '('),
 (313, 'email_sent_date'),
 (314, ')'),
 (315, ')'),
 (316, 'as'),
 (317, 'month_start_date'),
 (318, ','),
 (319,
  "-- dateadd(day, -1, dateadd(month,1,date_trunc('month',date(email_sent_date)))) as month_end_date,\n"),
 (320,
  "-- date_trunc('month', current_date) - interval 1 month as prev_mnth,\n"),
 (321, 'case'),
 (322, 'when'),
 (323, 'date_trunc'),
 (324, '('),
 (325, "'month'"),
 (326, ','),
 (327, 'current_date'),
 (328, ')'),
 (329, '='),
 (330, 'date_trunc'),
 (331, '('),
 (332, "'month'"),
 (333, ','),
 (334, 'email_sent_date'),
 (335, ')'),
 (336, 'then'),
 (337, "'C'"),
 (338, 'when'),
 (339, 'date_trunc'),
 (340, '('),
 (341, "'month'"),
 (342, ','),
 (343, 'current_date'),
 (344, ')'),
 (345, '-'),
 (346, 'interval'),
 (347, "'1'"),
 (348, 'month'),
 (349, '='),
 (350, 'date_trunc'),
 (351, '('),
 (352, "'month'"),
 (353, ','),
 (354, 'email_sent_date'),
 (355, ')'),
 (356, 'then'),
 (357, "'P'"),
 (358, 'when'),
 (359, 'date_trunc'),
 (360, '('),
 (361, "'month'"),
 (362, ','),
 (363, 'current_date'),
 (364, ')'),
 (365, '-'),
 (366, 'interval'),
 (367, "'2'"),
 (368, 'month'),
 (369, '='),
 (370, 'date_trunc'),
 (371, '('),
 (372, "'month'"),
 (373, ','),
 (374, 'email_sent_date'),
 (375, ')'),
 (376, 'then'),
 (377, "'PP'"),
 (378, 'when'),
 (379, 'date_trunc'),
 (380, '('),
 (381, "'month'"),
 (382, ','),
 (383, 'current_date'),
 (384, ')'),
 (385, '-'),
 (386, 'interval'),
 (387, "'3'"),
 (388, 'month'),
 (389, '='),
 (390, 'date_trunc'),
 (391, '('),
 (392, "'month'"),
 (393, ','),
 (394, 'email_sent_date'),
 (395, ')'),
 (396, 'then'),
 (397, "'PPP'"),
 (398, 'else'),
 (399, 'NULL'),
 (400, 'end'),
 (401, 'as'),
 (402, 'month_period'),
 (403, ','),
 (404, 'fae'),
 (405, '.'),
 (406, 'employee_key'),
 (407, 'FROM'),
 (408, 'analytics'),
 (409, '.'),
 (410, 'DIM_ACCOUNT'),
 (411, 'AS'),
 (412, 'da'),
 (413, 'INNER JOIN'),
 (414, 'analytics'),
 (415, '.'),
 (416, 'FACT_APPROVED_EMAIL'),
 (417, 'AS'),
 (418, 'fae'),
 (419, 'ON'),
 (420, 'da'),
 (421, '.'),
 (422, 'account_key'),
 (423, '='),
 (424, 'fae'),
 (425, '.'),
 (426, 'account_key'),
 (427, 'AND'),
 (428, 'da'),
 (429, '.'),
 (430, 'sys_current_flag'),
 (431, '='),
 (432, 'TRUE'),
 (433, 'LEFT JOIN'),
 (434, 'cte_dim_product'),
 (435, 'AS'),
 (436, 'dp'),
 (437, 'ON'),
 (438, 'dp'),
 (439, '.'),
 (440, 'product_key'),
 (441, '='),
 (442, 'fae'),
 (443, '.'),
 (444, 'product_key'),
 (445, 'AND'),
 (446, 'dp'),
 (447, '.'),
 (448, 'sys_current_flag'),
 (449, '='),
 (450, 'TRUE'),
 (451, 'LEFT JOIN'),
 (452, 'analytics'),
 (453, '.'),
 (454, 'vw_rep_account_product_segmentation'),
 (455, 'AS'),
 (456, 'vraps'),
 (457, 'ON'),
 (458, 'vraps'),
 (459, '.'),
 (460, 'product_key'),
 (461, '='),
 (462, 'fae'),
 (463, '.'),
 (464, 'product_key'),
 (465, 'AND'),
 (466, 'vraps'),
 (467, '.'),
 (468, 'account_key'),
 (469, '='),
 (470, 'fae'),
 (471, '.'),
 (472, 'account_key'),
 (473, 'LEFT JOIN'),
 (474, 'analytics'),
 (475, '.'),
 (476, 'map_territory_hierarchy'),
 (477, 'AS'),
 (478, 'mth'),
 (479, 'ON'),
 (480, 'fae'),
 (481, '.'),
 (482, 'territory_key'),
 (483, '='),
 (484, 'mth'),
 (485, '.'),
 (486, 'level1_territory_key'),
 (487, 'AND'),
 (488, 'mth'),
 (489, '.'),
 (490, 'sys_current_flag'),
 (491, '='),
 (492, 'true'),
 (493, 'LEFT JOIN'),
 (494, 'analytics'),
 (495, '.'),
 (496, 'dim_territory'),
 (497, 'AS'),
 (498, 'dt'),
 (499, 'ON'),
 (500, 'fae'),
 (501, '.'),
 (502, 'territory_key'),
 (503, '='),
 (504, 'dt'),
 (505, '.'),
 (506, 'territory_key'),
 (507, 'AND'),
 (508, 'dt'),
 (509, '.'),
 (510, 'sys_current_flag'),
 (511, '='),
 (512, 'true'),
 (513, 'LEFT JOIN'),
 (514, 'cte_region_territories'),
 (515, 'AS'),
 (516, 'rt'),
 (517, 'ON'),
 (518, 'rt'),
 (519, '.'),
 (520, 'level2_territory_key'),
 (521, '='),
 (522, 'fae'),
 (523, '.'),
 (524, 'territory_key'),
 (525, 'LEFT JOIN'),
 (526, 'analytics'),
 (527, '.'),
 (528, 'dim_country'),
 (529, 'as'),
 (530, 'dct'),
 (531, 'on'),
 (532, 'dct'),
 (533, '.'),
 (534, 'country_code'),
 (535, '='),
 (536, 'fae'),
 (537, '.'),
 (538, 'country_code'),
 (539, 'WHERE'),
 (540, '1'),
 (541, '='),
 (542, '1'),
 (543, 'and'),
 (544, 'fae'),
 (545, '.'),
 (546, 'business_function_key'),
 (547, '!='),
 (548, "'4'"),
 (549, 'and'),
 (550, '('),
 (551, 'fae'),
 (552, '.'),
 (553, 'territory_key'),
 (554, 'IS'),
 (555, 'NULL'),
 (556, 'OR'),
 (557, 'mth'),
 (558, '.'),
 (559, 'level1_territory_full_name'),
 (560, 'IS'),
 (561, 'NOT NULL'),
 (562, 'OR'),
 (563, 'rt'),
 (564, '.'),
 (565, 'level2_territory_key'),
 (566, 'IS'),
 (567, 'NOT NULL'),
 (568, ')')]

In [13]:
from sql_metadata import Parser

tokens = Parser(lines).tables
tokens

['analytics.map_territory_hierarchy',
 'analytics.dim_territory',
 'analytics.dim_product',
 'analytics.DIM_ACCOUNT',
 'analytics.FACT_APPROVED_EMAIL',
 'analytics.vw_rep_account_product_segmentation',
 'analytics.dim_country']

In [12]:
import sqlparse
parser2 = sqlparse.parse(lines)

#parser2[0].tokens

[<CTE 'WITH' at 0x7FF6ED9D4050>,
 <Whitespace ' ' at 0x7FF6ED9D40C0>,
 <Identifier 'cte_re...' at 0x7FF6EDA74450>,
 <Punctuation ',' at 0x7FF6ED9FF6E0>,
 <Newline ' ' at 0x7FF6ED9FF600>,
 <Whitespace ' ' at 0x7FF6ED9FF7C0>,
 <Newline ' ' at 0x7FF6ED9FF750>,
 <Comment '-- add...' at 0x7FF6EDA6B0D0>,
 <Identifier 'cte_di...' at 0x7FF6EDA757D0>,
 <Newline ' ' at 0x7FF6ED9EF980>,
 <Whitespace ' ' at 0x7FF6ED9EF830>,
 <Newline ' ' at 0x7FF6ED9EFA60>,
 <DML 'SELECT' at 0x7FF6ED9EFBB0>,
 <Newline ' ' at 0x7FF6ED9EFB40>,
 <Whitespace ' ' at 0x7FF6ED9EF0C0>,
 <Whitespace ' ' at 0x7FF6ED9EF130>,
 <IdentifierList ''-' as...' at 0x7FF6EDA7D050>,
 <Punctuation ',' at 0x7FF6EDA540C0>,
 <Whitespace ' ' at 0x7FF6EDA54130>,
 <Comment '-- mod...' at 0x7FF6EDA6B1D0>,
 <IdentifierList 'coales...' at 0x7FF6EDA7D4D0>,
 <Punctuation ',' at 0x7FF6EDA58670>,
 <Newline ' ' at 0x7FF6EDA58520>,
 <Whitespace ' ' at 0x7FF6EDA58750>,
 <Whitespace ' ' at 0x7FF6EDA587C0>,
 <Comment '-- dat...' at 0x7FF6EDA6B250>,
 <Identifier 'date_t...' at 0x7FF6EDA760D0>,
 <Punctuation '(' at 0x7FF6EDA589F0>,
 <IdentifierList ''year'...' at 0x7FF6EDA7D750>,
 <Punctuation ',' at 0x7FF6EDA59D70>,
 <Newline ' ' at 0x7FF6EDA59C20>,
 <Whitespace ' ' at 0x7FF6EDA59E50>,
 <Whitespace ' ' at 0x7FF6EDA59EC0>,
 <Comment '-- dat...' at 0x7FF6EDA6B2D0>,
 <IdentifierList 'case w...' at 0x7FF6EDA7DC50>,
 <Newline ' ' at 0x7FF6EDA5F0C0>,
 <Keyword 'FROM' at 0x7FF6EDA5F360>,
 <Whitespace ' ' at 0x7FF6EDA5F440>,
 <Identifier 'analyt...' at 0x7FF6EDA714D0>,
 <Newline ' ' at 0x7FF6EDA5F670>,
 <Keyword 'INNER ...' at 0x7FF6EDA5F7C0>,
 <Whitespace ' ' at 0x7FF6EDA5F8A0>,
 <Identifier 'analyt...' at 0x7FF6EDA71550>,
 <Newline ' ' at 0x7FF6EDA5FAD0>,
 <Whitespace ' ' at 0x7FF6EDA5FC90>,
 <Whitespace ' ' at 0x7FF6EDA5FD00>,
 <Keyword 'ON' at 0x7FF6EDA5FD70>,
 <Whitespace ' ' at 0x7FF6EDA5FDE0>,
 <Comparison 'da.acc...' at 0x7FF6EDA7B050>,
 <Newline ' ' at 0x7FF6EDA5FC20>,
 <Whitespace ' ' at 0x7FF6EDA612F0>,
 <Whitespace ' ' at 0x7FF6EDA61360>,
 <Keyword 'AND' at 0x7FF6EDA613D0>,
 <Whitespace ' ' at 0x7FF6EDA61440>,
 <Identifier 'da.sys...' at 0x7FF6EDA716D0>,
 <Whitespace ' ' at 0x7FF6EDA61600>,
 <Comparison '=' at 0x7FF6EDA61670>,
 <Whitespace ' ' at 0x7FF6EDA616E0>,
 <Keyword 'TRUE' at 0x7FF6EDA61750>,
 <Newline ' ' at 0x7FF6EDA61280>,
 <Keyword 'LEFT J...' at 0x7FF6EDA617C0>,
 <Whitespace ' ' at 0x7FF6EDA618A0>,
 <Identifier 'cte_di...' at 0x7FF6EDA763D0>,
 <Newline ' ' at 0x7FF6EDA619F0>,
 <Whitespace ' ' at 0x7FF6EDA61BB0>,
 <Whitespace ' ' at 0x7FF6EDA61C20>,
 <Keyword 'ON' at 0x7FF6EDA61C90>,
 <Whitespace ' ' at 0x7FF6EDA61D00>,
 <Comparison 'dp.pro...' at 0x7FF6EDA7B150>,
 <Newline ' ' at 0x7FF6EDA61B40>,
 <Whitespace ' ' at 0x7FF6EDA62210>,
 <Whitespace ' ' at 0x7FF6EDA62280>,
 <Keyword 'AND' at 0x7FF6EDA622F0>,
 <Whitespace ' ' at 0x7FF6EDA62360>,
 <Identifier 'dp.sys...' at 0x7FF6EDA71850>,
 <Whitespace ' ' at 0x7FF6EDA62520>,
 <Comparison '=' at 0x7FF6EDA62590>,
 <Whitespace ' ' at 0x7FF6EDA62600>,
 <Keyword 'TRUE' at 0x7FF6EDA62670>,
 <Newline ' ' at 0x7FF6EDA621A0>,
 <Keyword 'LEFT J...' at 0x7FF6EDA626E0>,
 <Whitespace ' ' at 0x7FF6EDA627C0>,
 <Identifier 'analyt...' at 0x7FF6EDA718D0>,
 <Newline ' ' at 0x7FF6EDA629F0>,
 <Whitespace ' ' at 0x7FF6EDA62BB0>,
 <Whitespace ' ' at 0x7FF6EDA62C20>,
 <Keyword 'ON' at 0x7FF6EDA62C90>,
 <Whitespace ' ' at 0x7FF6EDA62D00>,
 <Comparison 'vraps....' at 0x7FF6EDA7B1D0>,
 <Newline ' ' at 0x7FF6EDA62B40>,
 <Whitespace ' ' at 0x7FF6EDA63210>,
 <Whitespace ' ' at 0x7FF6EDA63280>,
 <Keyword 'AND' at 0x7FF6EDA632F0>,
 <Whitespace ' ' at 0x7FF6EDA63360>,
 <Comparison 'vraps....' at 0x7FF6EDA7B250>,
 <Newline ' ' at 0x7FF6EDA631A0>,
 <Keyword 'LEFT J...' at 0x7FF6EDA637C0>,
 <Whitespace ' ' at 0x7FF6EDA638A0>,
 <Identifier 'analyt...' at 0x7FF6EDA71B50>,
 <Newline ' ' at 0x7FF6EDA63AD0>,
 <Whitespace ' ' at 0x7FF6EDA63C90>,
 <Whitespace ' ' at 0x7FF6EDA63D00>,
 <Keyword 'ON' at 0x7FF6EDA63D70>,
 <Whitespace ' ' at 0x7FF6EDA63DE0>,
 <Comparison 'fae.te...' at 0x7FF6EDA7B2D0>,
 <Newline ' ' at 0x7FF6EDA63C20>,
 <Whitespace ' ' at 0x7FF6EDA642F0>,
 <Whitespace ' ' at 0x7FF6EDA64360>,
 <Keyword 'AND' at 0x7FF6EDA643D0>,
 <Whitespace ' ' at 0x7FF6EDA64440>,
 <Identifier 'mth.sy...' at 0x7FF6EDA71CD0>,
 <Whitespace ' ' at 0x7FF6EDA64600>,
 <Comparison '=' at 0x7FF6EDA64670>,
 <Whitespace ' ' at 0x7FF6EDA646E0>,
 <Keyword 'true' at 0x7FF6EDA64750>,
 <Newline ' ' at 0x7FF6EDA64280>,
 <Keyword 'LEFT J...' at 0x7FF6EDA647C0>,
 <Whitespace ' ' at 0x7FF6EDA648A0>,
 <Identifier 'analyt...' at 0x7FF6EDA71D50>,
 <Newline ' ' at 0x7FF6EDA64AD0>,
 <Whitespace ' ' at 0x7FF6EDA64C90>,
 <Whitespace ' ' at 0x7FF6EDA64D00>,
 <Keyword 'ON' at 0x7FF6EDA64D70>,
 <Whitespace ' ' at 0x7FF6EDA64DE0>,
 <Comparison 'fae.te...' at 0x7FF6EDA7B350>,
 <Newline ' ' at 0x7FF6EDA64C20>,
 <Whitespace ' ' at 0x7FF6EDA662F0>,
 <Whitespace ' ' at 0x7FF6EDA66360>,
 <Keyword 'AND' at 0x7FF6EDA663D0>,
 <Whitespace ' ' at 0x7FF6EDA66440>,
 <Identifier 'dt.sys...' at 0x7FF6EDA71ED0>,
 <Whitespace ' ' at 0x7FF6EDA66600>,
 <Comparison '=' at 0x7FF6EDA66670>,
 <Whitespace ' ' at 0x7FF6EDA666E0>,
 <Keyword 'true' at 0x7FF6EDA66750>,
 <Newline ' ' at 0x7FF6EDA66280>,
 <Keyword 'LEFT J...' at 0x7FF6EDA667C0>,
 <Whitespace ' ' at 0x7FF6EDA668A0>,
 <Identifier 'cte_re...' at 0x7FF6EDA76650>,
 <Newline ' ' at 0x7FF6EDA669F0>,
 <Whitespace ' ' at 0x7FF6EDA66BB0>,
 <Whitespace ' ' at 0x7FF6EDA66C20>,
 <Keyword 'ON' at 0x7FF6EDA66C90>,
 <Whitespace ' ' at 0x7FF6EDA66D00>,
 <Comparison 'rt.lev...' at 0x7FF6EDA7B3D0>,
 <Newline ' ' at 0x7FF6EDA66B40>,
 <Keyword 'LEFT J...' at 0x7FF6EDA67130>,
 <Whitespace ' ' at 0x7FF6EDA67210>,
 <Identifier 'analyt...' at 0x7FF6EDA740D0>,
 <Whitespace ' ' at 0x7FF6EDA67590>,
 <Keyword 'on' at 0x7FF6EDA67600>,
 <Whitespace ' ' at 0x7FF6EDA67670>,
 <Comparison 'dct.co...' at 0x7FF6EDA7B450>,
 <Newline ' ' at 0x7FF6EDA67440>,
 <Where 'WHERE ...' at 0x7FF6EDA6DE50>]